---
name: Create Pull Request Branch
on:
  workflow_dispatch:
    inputs:
      pr:
        description: 'Pull Request Number'
        required: true
permissions:
  id-token: write
  contents: read
  pull-requests: write
env:
  GITHUB_TOKEN: ${{github.token}}
  PR_NUMBER: ${{inputs.pr}}
  PR_BRANCH: pr/${{inputs.pr}}
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: gh auth setup-git
      # https://github.community/t/github-actions-bot-email-address/17204/5
      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - run: gh pr checkout "$PR_NUMBER"
      - run: echo "::set-output name=base_sha::$(git rev-parse HEAD)"
        id: base_sha
      - run: git fetch origin pull/${{inputs.pr}}/merge
      - run: git checkout -B "$PR_BRANCH" pull/${{inputs.pr}}/merge

      - run: |
          git ls-files | grep -E "/action\.yaml$" |
            xargs -n 1 sed -i "s|- uses: suzuki-shunsuke/tfaction/\(.*\)@main|- uses: suzuki-shunsuke/tfaction/\1@$branch|"
      - run: git ls-files | grep -E "/action\.yaml$" | xargs git add
      - run: |
          git commit -m "chore: test $PR_NUMBER
          base revision: ${{steps.base_sha.outputs.base_sha}}"
      - run: git push origin "$PR_BRANCH" --force
      - run: echo "[Pull Request](https://github.com/suzuki-shunsuke/tfaction/pull/$PR_NUMBER)" >> "$GITHUB_STEP_SUMMARY"
