---
name: Generate document from JSON Schema and deploy
on: workflow_call

jobs:
  deploy-schema:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: pip install json-schema-for-humans
      - run: mkdir build
      - run: generate-schema-doc --expand-buttons --link-to-reused-ref schema build

      - uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        if: github.event_name != 'pull_request'
        with:
          github_token: ${{ github.token }}
          publish_dir: ./build
          destination_dir: ./config
